config/routes.rb
Rails.application.routes.draw do
  root 'url_shortener#new'

  resources :url_shortener, only: [:show, :create], param: :short_id, path: '/'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/url_lookup.rb
class UrlLookup
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :url_lookup_metadatas, dependent: :destroy

  field :short_url, type: String
  field :target_url, type: String
  field :title, type: String

  validates :short_url, uniqueness: { allow_nil: true, message: I18n.t('errors.url_lookup.short_url.uniqueness') }
  validates :target_url, presence: true, on: %i[create_form create]
  validate :validate_target_url_format, on: [:create_form]
  validate :validate_target_url_ok, on: [:create_form]

  index({ short_url: 1 }, { unique: true, name: 'short_url_index' })

  def validate_target_url_format
    return if target_url.blank?

    uri = URI.parse(target_url)
    errors.add(:target_url, I18n.t('errors.url_lookup.target_url.format')) unless uri.is_a?(URI::HTTP) && !uri.host.nil?
  rescue URI::InvalidURIError
    errors.add(:target_url, I18n.t('errors.url_lookup.target_url.format'))
  end

  def validate_target_url_ok
    return if target_url.blank?

    res = Faraday.get(target_url)

    errors.add(:target_url, I18n.t('errors.url_lookup.target_url.invalid')) if res.blank? || res.status != 200
  rescue StandardError
    errors.add(:target_url, I18n.t('errors.url_lookup.target_url.invalid'))
  end
end

app/models/url_lookup_metadata.rb
class UrlLookupMetadata
  include Mongoid::Document

  belongs_to :url_lookup

  field :visited_at, type: DateTime
  field :ip_address, type: String
  field :country, type: String

  validates :visited_at, presence: true
  validates :ip_address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/url_shortener_controller.rb
class UrlShortenerController < ApplicationController
  def show
    @url_lookup = UrlLookupGetService.new.get_url_lookup(short_id: params[:short_id])

    if @url_lookup.nil?
      flash[:error] = I18n.t('errors.url_lookup.not_found')
      return redirect_to root_path
    end

    UrlLookupMetadataService.new.record_visit(url_lookup: @url_lookup, ip_address: request.remote_ip)

    redirect_to @url_lookup[:target_url], allow_other_host: true
  end

  def new
    @created_url_lookup = if params.key?(:created_short_url)
                            UrlLookupGetService.new.get_url_lookup(short_url: params[:created_short_url])
                          end
    @url_lookup = UrlLookup.new
  end

  def create
    create_service = UrlLookupCreateService.new(create_url_lookup_params)

    unless create_service.valid?
      @url_lookup = create_service.url_lookup
      render :new, status: :bad_request
      return
    end

    created_url_lookup = create_service.create!

    redirect_to root_path(created_short_url: created_url_lookup[:short_url])
  end

  private

  def create_url_lookup_params
    params.require(:url_lookup).permit(:target_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Url Shortener</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<main class="container mx-auto mt-28 px-4 md:px-32 w-full flex flex-col space-y-12">
  <%= yield %>
</main>
</body>
</html>

app/views/shared/_readonly_field.html.erb
<div class="flex flex-col w-96 justify-between">
  <p class="label"><%= field_label %></p>
  <p><%= field_value %></p>
</div>

app/views/shared/_readonly_link.html.erb
<div class="flex flex-col w-96 justify-between">
  <p class="label"><%= field_label %></p>
  <a class="link" href="<%= field_value %>" target='_blank'><%= field_value %></a>
</div>

app/views/url_shortener/_new_form.html.erb
<div class="container">
  <p class="h2">Shorten your long URL here</p>
  <%= form_with(model: url_lookup, url: url_shortener_index_path, class: 'form-control') do |form| %>
    <% errors = url_lookup.errors %>
    <div>
      <%= form.label :target_url, style: "display: block", class: "label" %>
      <%= form.text_field :target_url, class: class_names('input', errors.key?(:target_url) ? 'input-error' : ''), placeholder: 'e.g. https://www.google.com' %>
      <span class="input-error-msg"><%= errors.full_messages_for(:target_url).first %></span>
    </div>
    <div>
      <%= form.submit "Shorten!", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/url_shortener/_url_lookup_details.html.erb
<div class="container">
  <p class="h2"><%= title %></p>
  <div class="flex flex-col space-y-4">
    <%= render 'shared/readonly_link', field_label: 'Short URL', field_value: url_lookup.short_url %>
    <%= render 'shared/readonly_field', field_label: 'Target URL', field_value: url_lookup.target_url %>
    <%= render 'shared/readonly_field', field_label: 'Title', field_value: url_lookup.title %>
  </div>
</div>

app/views/url_shortener/new.html.erb
<% if flash[:error].present? %>
  <div class="alert-bar">
    <span class="alert-message"><%= flash[:error] %></span>
  </div>
<% end %>


<%= render 'new_form', url_lookup: @url_lookup %>

<% if @created_url_lookup %>
  <%= render 'url_lookup_details', url_lookup: @created_url_lookup, title: 'Created URL' %>
<% end %>